import './nodes/GroupNode.js';import './nodes/ShapeNode.js';import './nodes/TextNode.js';import './nodes/ImageNode.js';
import { StudioDocument } from './document/Document.js';import { Scene } from './core/Scene.js';import { AssetManager } from './assets/AssetManager.js';import { CanvasRenderer } from './rendering/CanvasRenderer.js';import { ExportRenderer } from './rendering/ExportRenderer.js';import { CommandManager } from './commands/CommandManager.js';import { UpdatePropertyCommand,ReorderNodeCommand } from './commands/Commands.js';import { SelectTool } from './interaction/SelectTool.js';import { TemplateManager } from './templates/TemplateManager.js';import { FontManager } from './fonts/FontManager.js';import { removeLightBackground } from './image/BackgroundRemover.js';
const $=s=>document.querySelector(s),canvas=$('#studioCanvas'),assets=new AssetManager(),fonts=new FontManager();let activeTemplate='editorial-quote-reference';let documentModel=new StudioDocument({scene:TemplateManager.createScene(activeTemplate)});const renderer=new CanvasRenderer(canvas,documentModel.scene,assets);const commands=new CommandManager(()=>{documentModel.scene.emit('changed');renderLayers();renderInspector()});const selectTool=new SelectTool(renderer,documentModel.scene,commands);
function status(s){$('#status').textContent=s}function activeNode(){return documentModel.scene.getSelectedNodes()[0]??null}function emit(){documentModel.scene.emit('changed');renderLayers();renderInspector()}
function bindScene(scene){documentModel.replaceScene(scene);renderer.bindScene(scene);selectTool.bindScene(scene);commands.clear();scene.on('selectionChanged',()=>{renderLayers();renderInspector()});emit()}
async function loadReference(){try{const img=await fetch('./assets/reference/editorial-quote-reference.jpg').then(r=>r.blob());const file=new File([img],'reference.jpg',{type:'image/jpeg'});const asset=await assets.addImageFile(file,'reference-portrait');const n=documentModel.scene.findById('portrait');n.assetId=asset.id;n.originalAssetId=asset.id;emit()}catch{}}
function allNodes(){return documentModel.scene.root.children.slice().sort((a,b)=>b.zIndex-a.zIndex)}
function renderLayers(){const list=$('#layerList');list.innerHTML='';for(const node of allNodes()){const el=document.createElement('div');el.className=`layer-item ${activeNode()?.id===node.id?'active':''}`;el.innerHTML=`<span class="layer-icon">${node.type==='text'?'T':node.type==='image'?'IMG':'▭'}</span><span>${node.name}<small>${node.type}</small></span><span>${node.locked?'🔒':node.visible?'◉':'○'}</span>`;el.onclick=()=>documentModel.scene.selectOnly(node);list.appendChild(el)}}
const tf={name:$('#nodeName'),x:$('#nodeX'),y:$('#nodeY'),width:$('#nodeWidth'),height:$('#nodeHeight'),rotation:$('#nodeRotation'),opacity:$('#nodeOpacity')};
function renderInspector(){const n=activeNode();$('#emptyInspector').hidden=!!n;$('#nodeInspector').hidden=!n;if(!n)return;for(const [k,f] of Object.entries(tf))f.value=k==='name'?n[k]:Math.round((n[k]??0)*100)/100;if(n.type==='text'){$('#nodeText').value=n.text;$('#fontFamily').value=[...$('#fontFamily').options].some(o=>o.value===n.fontFamily)?n.fontFamily:$('#fontFamily').value;$('#fontSize').value=n.fontSize;$('#fontWeight').value=n.fontWeight;$('#lineHeight').value=n.lineHeight;$('#letterSpacing').value=n.letterSpacing;$('#textAlign').value=n.textAlign;$('#textColor').value=n.color}if(n.type==='image'){$('#imageBrightness').value=n.brightness;$('#imageContrast').value=n.contrast;$('#imageZoom').value=n.zoom;$('#imageRadius').value=n.radius;$('#portraitShadow').checked=n.shadow}}
function change(key,value){const n=activeNode();if(!n||n.locked)return;const before=n[key];if(before===value)return;commands.execute(new UpdatePropertyCommand(n,key,before,value,emit))}
for(const [k,f] of Object.entries(tf))f.addEventListener('change',()=>change(k,k==='name'?f.value:Number(f.value)));
[['nodeText','text',String],['fontFamily','fontFamily',String],['fontSize','fontSize',Number],['fontWeight','fontWeight',Number],['lineHeight','lineHeight',Number],['letterSpacing','letterSpacing',Number],['textAlign','textAlign',String],['textColor','color',String],['imageBrightness','brightness',Number],['imageContrast','contrast',Number],['imageZoom','zoom',Number],['imageRadius','radius',Number]].forEach(([id,key,parse])=>$('#'+id).addEventListener(id.startsWith('image')?'input':'change',()=>change(key,parse($('#'+id).value))));$('#portraitShadow').onchange=()=>change('shadow',$('#portraitShadow').checked);
for(const tab of document.querySelectorAll('.tab'))tab.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(e=>e.classList.remove('active'));tab.classList.add('active');$('#panel-'+tab.dataset.panel).classList.add('active')};
for(const card of document.querySelectorAll('.template-card'))card.onclick=()=>{document.querySelectorAll('.template-card').forEach(e=>e.classList.remove('active'));card.classList.add('active');activeTemplate=card.dataset.template;const old=documentModel.scene.findById('portrait');bindScene(TemplateManager.createScene(activeTemplate,old?.assetId??null));const n=documentModel.scene.findById('portrait');if(n)n.originalAssetId=old?.originalAssetId??old?.assetId??null;status('Template applied')};
$('#imageUpload').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;const a=await assets.addImageFile(file);const n=documentModel.scene.findById('portrait');n.assetId=a.id;n.originalAssetId=a.id;emit();status('Portrait uploaded')};
$('#removeBackground').onclick=async()=>{const n=documentModel.scene.findById('portrait');const a=assets.get(n?.originalAssetId??n?.assetId);if(!a)return status('Upload a portrait first');status('Removing light background…');const data=await removeLightBackground(a.data,Number($('#removeThreshold').value),Number($('#removeFeather').value));const cut=await assets.addImageDataUrl(crypto.randomUUID(),data);n.assetId=cut.id;emit();$('#removeBackground').classList.add('active');$('#useOriginal').classList.remove('active');status('Light background removed')};
$('#useOriginal').onclick=()=>{const n=documentModel.scene.findById('portrait');if(n?.originalAssetId){n.assetId=n.originalAssetId;emit()}$('#useOriginal').classList.add('active');$('#removeBackground').classList.remove('active')};
$('#removeThreshold').oninput=()=>$('#thresholdValue').value=$('#removeThreshold').value;$('#removeFeather').oninput=()=>$('#featherValue').value=$('#removeFeather').value;
$('#fontUpload').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const item=await fonts.addFile(f);const o=new Option(item.family,item.family);$('#fontFamily').add(o);$('#fontFamily').value=item.family;const n=activeNode();if(n?.type==='text'&&!n.locked)change('fontFamily',item.family);$('#fontStatus').textContent=`Loaded: ${item.name}. The font is embedded in saved project files.`;status('Custom font loaded')}catch(err){status(err.message)}};
$('#brandName').onchange=()=>{const n=documentModel.scene.findById('brand');if(n){n.text=$('#brandName').value;emit()}};$('#accentColor').oninput=()=>{for(const id of ['divider','speaker','role','brand-line','date']){const n=documentModel.scene.findById(id);if(n)n[n.type==='shape'?'fill':'color']=$('#accentColor').value}emit()};$('#canvasBackground').oninput=()=>{const c=$('#canvasBackground').value;documentModel.scene.backgroundColor=c;const bg=documentModel.scene.findById('background');if(bg){bg.fill=c;bg.visible=true}$('#transparentCanvas').checked=false;emit()};$('#transparentCanvas').onchange=()=>{const on=$('#transparentCanvas').checked;documentModel.scene.backgroundColor=on?'transparent':$('#canvasBackground').value;const bg=documentModel.scene.findById('background');if(bg)bg.visible=!on;emit()};$('#lockBrand').onchange=()=>{for(const id of ['brand','brand-line','date']){const n=documentModel.scene.findById(id);if(n)n.locked=$('#lockBrand').checked}emit()};
$('#bringForward').onclick=()=>reorder(1);$('#sendBackward').onclick=()=>reorder(-1);function reorder(d){const n=activeNode();if(!n?.parent||n.locked)return;const from=n.parent.children.indexOf(n),to=Math.max(0,Math.min(n.parent.children.length-1,from+d));if(from!==to)commands.execute(new ReorderNodeCommand(documentModel.scene,n,from,to))}$('#toggleLock').onclick=()=>{const n=activeNode();if(n){n.locked=!n.locked;emit()}};$('#toggleVisibility').onclick=()=>{const n=activeNode();if(n){n.visible=!n.visible;emit()}};$('#undo').onclick=()=>commands.undo();$('#redo').onclick=()=>commands.redo();
$('#formatSelect').onchange=e=>{const v=e.target.value;activeTemplate=v==='1080x1080'?'editorial-quote-square':v==='1080x1350'?'editorial-quote-portrait':'editorial-quote-reference';const old=documentModel.scene.findById('portrait');bindScene(TemplateManager.createScene(activeTemplate,old?.assetId??null));status('Canvas format changed')};$('#newDocument').onclick=()=>{bindScene(TemplateManager.createScene(activeTemplate));loadReference();status('Template reset')};
$('#exportPng').onclick=async()=>{await ExportRenderer.exportPNG(documentModel.scene,assets);status('PNG downloaded')};$('#saveProject').onclick=()=>{const data=documentModel.toJSON(assets);data.version=2;data.fonts=fonts.toJSON();download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'naappe-publisher-project.json')};$('#loadProject').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const data=JSON.parse(await f.text());await assets.loadJSON(data.assets??[]);await fonts.loadJSON(data.fonts??[]);documentModel=new StudioDocument({id:data.id,name:data.name,scene:Scene.fromJSON(data.scene)});bindScene(documentModel.scene);status('Project loaded')};function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
window.addEventListener('resize',()=>renderer.resize());documentModel.scene.on('selectionChanged',()=>{renderLayers();renderInspector()});renderLayers();renderInspector();loadReference();
